// Code generated by goro;

package accrualservice

import "gophermart/internal/entity"

// This file was generated by the goro tool.

type accrualRepo interface {
	GetOrderAccrual(orderID string) (entity.Accrual, error)
}

type Service struct {
	accrualRepo accrualRepo
}

func NewService(accrualRepo accrualRepo) *Service {
	return &Service{

		accrualRepo: accrualRepo,
	}
}
