// Code generated by goro;

package orderservice

// This file was generated by the goro tool.

import (
	"context"
	"gophermart/internal/entity"
	"gophermart/internal/service"
)

type orderRepo interface {
	service.Transactor
	CreateOrder(ctx context.Context, orderID string, userID int64, status entity.OrderStatus, accrual float64) (int64, error)
	GetByOrderID(ctx context.Context, orderID string) (entity.Order, error)
	GetByUserID(ctx context.Context, userID int64) ([]entity.Order, error)
	UpdateStatus(ctx context.Context, orderID string, status entity.OrderStatus) error
	UpdateStatusAndAccrual(ctx context.Context, orderID string, status entity.OrderStatus, accrual float64) error
}

type Service struct {
	orderRepo orderRepo
}

func NewService(orderRepo orderRepo) *Service {
	return &Service{
		orderRepo: orderRepo,
	}
}
