// Code generated by goro;

package operationservice

// This file was generated by the goro tool.

import (
	"context"
	"gophermart/internal/entity"
	"gophermart/internal/service"
)

type operationRepo interface {
	service.Transactor
	GetBalanceByUserID(ctx context.Context, userID int64) (entity.BalanceResponse, error)
	CreateOperation(ctx context.Context, orderID string, userID int64, operationType entity.OperationType, sum float64) (int64, error)
	GetOperationsByUserID(ctx context.Context, userID int64, operationType entity.OperationType) ([]entity.Operation, error)
}

type Service struct {
	operationRepo operationRepo
}

func NewService(operationRepo operationRepo) *Service {
	return &Service{

		operationRepo: operationRepo,
	}
}
